### ISSUE TITLE
PostgreSQL failed to restore dump file backup_so_march_2017_stemmed_stoped_ok.backup

### ISSUE THREAD

**Issue by lucky-liwenlong** [muldon/dupeRep#3]
![image](https://user-images.githubusercontent.com/57584750/99207073-fd006900-27f7-11eb-9826-7c71a318130f.png)
![image](https://user-images.githubusercontent.com/57584750/99207296-8d3eae00-27f8-11eb-9f8d-45c5e4e40b35.png)
I used the file ‘backup_so_march_2017_stemmed_stoped_ok.backup’ you provided, but postgresql cannot recover the file successfully

**Comment by muldon** [comment]
check your postgres version, as I mentioned on the readme, the version must be 9.3.
